### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by i3bot** [i3/i3#523]
[Originally reported by charles.gagalac@…]
(i'm unable to build git version 4.0.2-155-g5a85c9e and get the following error:

```
echo "YACC src/cfgparse.y"
YACC src/cfgparse.y
bison --debug --verbose -b src/cfgparse  -d src/cfgparse.y
cc -DXCB_COMPAT -DI3_VERSION=\""4.0.2-155-g5a85c9e (2011-09-14, branch \\\"next\\\")"\" -DSYSCONFDIR=\"/etc\" -DTERM_EMU=\"xterm\" -D_GNU_SOURCE -O2 -march=i486 -mtune=i686 -std=c99 -pipe -Wall -Wunused-value -Iinclude                       -idirafter /tmp/SBo/i3-next.110914T143629/yajl-fallback -gdwarf-2 -g3 -DLOGLEVEL="(1 << 3)" -c -o src/cfgparse.y.o src/cfgparse.tab.c
src/cfgparse.y:248:34: error: expected declaration specifiers or '...' before 'ev_cleanup'
src/cfgparse.y: In function 'start_configerror_nagbar':
src/cfgparse.y:301:5: error: 'ev_cleanup' undeclared (first use in this function)
src/cfgparse.y:301:5: note: each undeclared identifier is reported only once for each function it appears in
src/cfgparse.y:301:17: error: 'cleanup' undeclared (first use in this function)
src/cfgparse.y:302:5: warning: implicit declaration of function 'ev_cleanup_init'
src/cfgparse.y:303:5: warning: implicit declaration of function 'ev_cleanup_start'
make: *** [src/cfgparse.y.o] Error 1
```

i bisected the next branch down to the following commit:

```
d03dffe012ca1807b396270a4b145bfb0ae6d63a is the first bad commit
commit d03dffe012ca1807b396270a4b145bfb0ae6d63a
Author: Michael Stapelberg <michael@…>
Date:   Sun Sep 11 21:49:35 2011 +0100

    Kill left-over i3-nagbar processes on 'exit'

:040000 040000 63f7b9ff8efb1862ef82101a6d535ec65f77efc0 99df121e7e6a270e67518d066e27a134488f5a1b M       src

```
