### ISSUE TITLE
4.25 unconditionally uses `uselocale()`

### ISSUE THREAD

**Issue by 0-wiz-0** [i3/i3#6566]
### Welcome

- [x] Yes, I'm using the latest major release or the current development version. These are the only supported versions.
- [x] Yes, I've searched similar issues and discussions on GitHub and didn't find any.

### Current Behavior

I'm trying to update i3wm in pkgsrc to 4.25, but the build fails with:
```
../src/ipc.c: In function 'handle_tree':
../src/ipc.c:912:28: error: implicit declaration of function 'uselocale'; did you mean 'setlocale'? [-Wimplicit-function-declaration]
  912 |     locale_t prev_locale = uselocale(numericC);
      |                            ^~~~~~~~~
      |                            setlocale
```
and many similar lines.

NetBSD does not provide `uselocale`.

### Expected Behavior

It would be good if the build checked for `uselocale` and only used it if the system provides it.

### Reproduction Instructions

Try building on NetBSD, in my case NetBSD 11.99.4/x86_64.

### i3 version

```text
From the last successfully building version:

Binary i3 version:  4.24 (2024-11-06) © 2009 Michael Stapelberg and contributors

but 4.25 doesn't build.
```

### Config file

```text
n/a
```

### Linux distribution & Version

pkgsrc on NetBSD

### Are you using a compositor?

Other

**Comment by 0-wiz-0** [comment]
Hm, why was this auto-closed?

**Comment by orestisfl** [comment]
@stapelberg can you take a look here? This was introduced by https://github.com/i3/i3/commit/5446ea33e

**Comment by stapelberg** [comment]
Ah, man, I saw that [uselocale is in POSIX 2008](https://pubs.opengroup.org/onlinepubs/9799919799/functions/uselocale.html) and spot-checked a few BSDs, but obviously not NetBSD.

I guess we should just use setlocale then, until perhaps we no longer need to care about locales after switching JSON libraries (issue #6257). PRs welcome.

**Comment by 0-wiz-0** [comment]
@stapelberg Thanks for the feedback. I've just opened a PR.

**Comment by 0-wiz-0** [comment]
Thank you, @stapelberg !
