### ISSUE TITLE
i3-next (load_layout.c) doesn't compile with yajl 1.0.12-2

### ISSUE THREAD

**Issue by i3bot** [i3/i3#1156]
[Originally reported by i3@…]
(`yajl_config` is a yajl 2.0 feature afaict. I can compile `master` fine on this old Ubuntu dist.

```
pbos@…
[i3] PCH all.h
[i3] CC src/assignments.c
[i3] CC src/click.c
[i3] CC src/commands.c
[i3] CC src/commands_parser.c
[i3] CC src/con.c
[i3] CC src/config.c
[i3] CC src/config_directives.c
[i3] CC src/config_parser.c
[i3] CC src/debug.c
[i3] CC src/display_version.c
[i3] CC src/ewmh.c
[i3] CC src/fake_outputs.c
[i3] CC src/floating.c
[i3] CC src/handlers.c
[i3] CC src/ipc.c
[i3] CC src/key_press.c
[i3] CC src/load_layout.c
../i3/src/load_layout.c:438:5: warning: implicit declaration of function 'yajl_config' is invalid in C99 [-Wimplicit-function-declaration]
    yajl_config(hand, yajl_allow_comments, true);
    ^
../i3/src/load_layout.c:438:23: error: use of undeclared identifier 'yajl_allow_comments'
    yajl_config(hand, yajl_allow_comments, true);
                      ^
../i3/src/load_layout.c:440:23: error: use of undeclared identifier 'yajl_allow_multiple_values'
    yajl_config(hand, yajl_allow_multiple_values, true);
                      ^
1 warning and 2 errors generated.
make: *** [src/load_layout.o] Error 1
```

```
pbos@… 
Package: libyajl-dev
Architecture: amd64
Depends: libyajl1 (= 1.0.12-2)
Description: Yet Another JSON Library - development files
 A small, fast library for parsing JavaScript Object Notation (JSON).  It
 supports incremental parsing from a stream and leaves data representation to
 higher level code.
 .
 This package contains the header files and static libraries needed for
 compiling software that uses the yajl library.
Filename: pool/libyajl-dev_1.0.12-2_amd64_8f0116133fc215f994bc751c760e7cd8ced442b4ee86a142b0b47a9d7f844ba4.deb
Homepage: http://lloyd.github.com/yajl/
Installed-Size: 122
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@…>
Original-Maintainer: John Stamp <jstamp@…>
Priority: extra
SHA256: 8f0116133fc215f994bc751c760e7cd8ced442b4ee86a142b0b47a9d7f844ba4
Section: libdevel
Size: 22004
Source: yajl
Version: 1.0.12-2
```
