### ISSUE TITLE
Documentation should discourage from using `--depth 1` when cloning

### ISSUE THREAD

**Issue by Polymehr** [i3/i3#3861]
## I'm submitting a…

<pre>
[ ] Bug
[ ] Feature Request
[x] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
The [official website](https://i3wm.org/docs/hacking-howto.html) and the [wiki](https://github.com/Airblader/i3/wiki/Building-from-source) do not mention that using `--depth 1` when cloning the repository can result in an compilation error as mentioned in issue [#163](https://github.com/Airblader/i3/issues/163) from Airblader's fork with the same issue. (Maybe this is also related to issue #2833).

## Expected Behavior
The [official website](https://i3wm.org/docs/hacking-howto.html) and the [wiki](https://github.com/Airblader/i3/wiki/Building-from-source) should mention this fix which was recommended by [this](https://github.com/Airblader/i3/issues/163#issuecomment-419654501) user (and worked for me).

**Comment by Airblader** [comment]
Thanks for taking time to open this. In general I don't believe in documenting everything you cannot / shouldn't do because that list is long, but in this case I don't mind adding a hint to the hacking howto. Feel free to send a PR. 

We don't recommend users compile on their own, though, unless they want to contribute. Installing i3 should be done through packages.

I'll close this issue because I don't think there's long standing value in it but as I said if you want to add a sentence to the hacking howto we can get it merged. Thanks!
